markdown : kramdown
highligher : true

permalink : /:year/:month/:title/

title       : Working Bastard
tagline     :
description :
url         : http://blog.youknowmymind.com

author :
  name : hbc
  url  : https://twitter.com/artofhuh

paginate : 1000000000

github  : bcho
twitter : "@artofhuh"
